### ISSUE TITLE
`mkdocs` does not watch for file changes when using `click>8.2.1`

### ISSUE THREAD

**Issue by oliversheridanmethven** [mkdocs/mkdocs#4032]
I noticed when I did a dependency upgrade to some of the latest and greatest, that `mkdocs` was no longer watching for file changes. Eventually I narrows this down. With `click==8.2.1` everything works and file changes trigger everything to reload. However, when this gets bumped to `click=8.3.0` no files are being watched and no dynamic doc reloading when doing a `mkdocs serve`. 

It is likely related to this issue: https://github.com/mkdocs/mkdocs/issues/4014

Can we pin to 8.2.1 as a hot-fix until this is resolved?

**Comment by jcwomack** [comment]
I encountered this issue, too, and can confirm that rolling back to `click==8.2.1` restored previous file watching behaviour for `mkdocs serve`.

**Comment by facelessuser** [comment]
It sounds like you would need to exclude 8.2.2 as well?

**Comment by pawamoy** [comment]
It's yanked but yeah for good measure 🙂

**Comment by lovelydinosaur** [comment]
Is this specifically an issue because both of these flag values are declared?...

```python
@click.option('--no-livereload', 'livereload', flag_value=False, help=no_reload_help)
@click.option('--livereload', 'livereload', flag_value=True, default=True, hidden=True)
```

...that does look odd to me, despite https://github.com/pallets/click/issues/3084 indicating that this is a click issue.

It'd be helpful to first get guidance from their team since that's where the behavioural change has come from.

**Comment by marlon-tucker** [comment]
@lovelydinosaur 

This setup is almost explicitly stated like for like in their documentation:

https://click.palletsprojects.com/en/stable/options/#flag-value

However... they also have an dedicated mechanism for boolean option types

https://click.palletsprojects.com/en/stable/options/#boolean

Which would make the above code look more like this:

```php
@click.option('--livereload/--no-livereload', 'livereload', default=True)
```

The only downside is I don't see a way to hide the `--livereload` option from presumably the help text. But IMO that isn't the end of the world.

**Comment by rhjdjong** [comment]
I encountered the same issue. After some experimenting, I found that changing the order of the two lines in `__main__.py` gives the desired behaviour. So: 

```
@click.option('--livereload', 'livereload', flag_value=True, default=True, hidden=True)
@click.option('--no-livereload', 'livereload', flag_value=False, help=no_reload_help)
``

**Comment by marlon-tucker** [comment]
Thinking about it more, I don't see the point of the `--livereload` flag? If the default value is `True` and passing it in sets it  to `True` as well, its effectively redundant. 

I suggest the live reload mechanism is controlled by a local variable instead and the `--no-livereload` flag can set a `disableLiveReload` parameter.

aka
```
var liveReload = true
if (disableLiveReload) 
    liveReleod = false
```

This would also keep only the `--no-livereload` option in the help text like it is now.

**Comment by drdv** [comment]
If there is no reason to have a hidden flag `--livereload` (which "reaffirms" the intended default benaviour), we could simply do:

```python
import click

@click.command()
@click.option("--no-livereload", is_flag=True, default=False, help="Disable livereload")
def main(no_livereload):
    print("DISABLED") if no_livereload else print("ENABLED")

if __name__ == "__main__":
    main()
```
Not fancy, but works with both `click v8.1.7` and `click v8.3.0`

**Comment by jstebenne** [comment]
I haven't tested, but if @rhjdjong's suggestion works, I think it should be easy enough to get this reviewed and merged to fix the bug. Other improvements can follow in a separate issue or PR

**Comment by marlon-tucker** [comment]
Just changing the order of the attributes seems very flaky to me.

**Comment by jstebenne** [comment]
I agree, and a better solution **must** be implemented. I'm just suggesting that the discussion to find what is better should not prevent the bug to be fixed.

**Comment by smartYSC** [comment]
Maybe I can point you to this discussion I opened in typer for the same reason:
https://github.com/fastapi/typer/discussions/1355

TL;DR: Pin a maximum version of click. They are not doing semantic versioning (stated in their docs) and their code breaks compatibility at any time. Typer was affected by this multiple times already.

**Comment by lovelydinosaur** [comment]
> I haven't tested, but if @rhjdjong's suggestion works, I think it should be easy enough to get this reviewed and merged to fix the bug. Other improvements can follow in a separate issue or PR

That would be a reasonable compromise for now.
If someone would like to issue that PR, I can look at merging and issuing a new release.

**Comment by johnthagen** [comment]
> If someone would like to issue that PR, I can look at merging and issuing a new release.

@lovelydinosaur I attempted to do this in 

- #4058

There are a couple CI jobs failing that I _think_ are unrelated (e.g., PyPy on Windows?) that I don't know how to address and would need help. Feel free to push to that PR if you'd like.

**Comment by dotlambda** [comment]
> Relevant Click issue: [pallets/click#3084](https://github.com/pallets/click/issues/3084)

I'm pretty sure the actual issue is https://github.com/pallets/click/issues/3111.
EDIT: Well, at least something related to it.

**Comment by jaredrummler** [comment]
## Workaround: Auto-restart script for macOS users

For those on macOS who can't downgrade Click due to dependency conflicts (e.g., other packages requiring `click>=8.3.1`), here's a bash script that works around the issue by auto-restarting the MkDocs server when files change:

```bash
#!/bin/bash
# Auto-restart MkDocs server when docs/overrides changes
# This works around the Click 8.3.x bug that breaks MkDocs watch functionality

set -e

SERVER_PID=""

# Cleanup function
cleanup() {
  echo -e "\nShutting down server..."
  if [ ! -z "$SERVER_PID" ]; then
    kill $SERVER_PID 2>/dev/null || true
  fi
  exit 0
}

# Set up trap for clean exit
trap cleanup SIGINT SIGTERM

# Function to start server
start_server() {
  echo "Starting MkDocs server..."
  mkdocs serve &
  SERVER_PID=$!
  echo "Server running at http://127.0.0.1:8000 (PID: $SERVER_PID)"
}

# Function to restart server
restart_server() {
  echo "Changes detected, restarting server..."
  if [ ! -z "$SERVER_PID" ]; then
    kill $SERVER_PID 2>/dev/null || true
    sleep 1
  fi
  start_server
}

# Check if fswatch is installed (macOS)
if ! command -v fswatch &> /dev/null; then
  echo "fswatch is not installed. Install via: brew install fswatch"
  exit 1
fi

# Start initial server
start_server

# Watch for changes and restart
echo "Watching docs/ for changes... Press Ctrl+C to stop"
fswatch -o docs | while read; do
  restart_server
done
```

**Usage:**
```bash
chmod +x watch-docs.sh
./watch-docs.sh
```

This completely bypasses the Click bug by managing the server lifecycle externally. Uses `fswatch` on macOS (install via `brew install fswatch`).

**Root Cause:**
The issue is caused by Click 8.3.0+ breaking the `flag_value` option handling (see https://github.com/pallets/click/issues/3084). The fix has been merged in Click PR #3152 but **not yet released**. Once Click 8.3.2+ is released with the fix, or MkDocs constrains Click to `<=8.2.1` (PR #4058), this workaround won't be necessary.

**Comment by PowerKiKi** [comment]
The simpler workaround is to specify explicitly to live reload with `mkdocs serve --livereload`

**Comment by hheimbuerger** [comment]
> The simpler workaround is to specify explicitly to live reload with `mkdocs serve --livereload`

That's an undocumented option, though, isn't it? I can't find that, neither in the `--help`, nor on [mkdocs.org](https://www.mkdocs.org/user-guide/cli/).

**Comment by drdv** [comment]
It has been defined as `hidden=True`
https://github.com/mkdocs/mkdocs/blob/2862536793b3c67d9d83c33e0dd6d50a791928f8/mkdocs/__main__.py#L257

Can someone explain why?

**Comment by Wcowin** [comment]
## MkDocs Hot Update Failure Issue

### Problem Description

After running `mkdocs serve`, when modifying a Markdown file and saving it, the terminal does not display `Detected file changes`, and the browser will not refresh automatically.

### Reason

**Bug in click 8.3.x version** causes MkDocs' livereload file monitoring feature to fail.

Related Issue: [MkDocs use_directory_urls: true bug with click==8.2.2 #4014](https://github.com/mkdocs/mkdocs/issues/4014)

### Solution

Downgrade click to version 8.2.1:

```bash
pip install click==8.2.1
```

**Comment by DrewScatterday** [comment]
> mkdocs serve --livereload

This worked for me as a workaround 😄

**Comment by jaywhj** [comment]
The bug has been fixed.

See  https://github.com/pallets/click/pull/3152

Now waiting for click 8.3.2 to be released

**Comment by Rapture244** [comment]
> The simpler workaround is to specify explicitly to live reload with `mkdocs serve --livereload`

Amazing, the answer was so simple, it works like a charm !

**Comment by johnthagen** [comment]
According to a `click` maintainer, there will be no more bug fix releases for `click` before v9

- https://github.com/pallets/click/issues/3107#issuecomment-3830687046

**Comment by portg80** [comment]
I installed mkdocs and I also didn't have auto-updates when I changed files, so I rolled back click:
```
py -m pip install "click==8.2.1"
```
and the problem immediately disappeared. I really don't know what this could lead to

**Comment by neriyaco** [comment]
If anyone uses `uv` you can add this to your `pyproject.toml`

```toml
[tool.uv]
constraint-dependencies = [
  "click<=8.2.1"
]
```

**Comment by jaywhj** [comment]
This bug is already fixed in a fork, and the fix is already included in the [latest release](https://github.com/ProperDocs/properdocs/releases) 

* https://github.com/ProperDocs/properdocs/pull/14

Please check it out! It's a complete drop-in replacement, you just `pip install properdocs` instead.

* https://github.com/ProperDocs/properdocs
* https://github.com/ProperDocs/properdocs/discussions/33

**Comment by markuspi** [comment]
Click 8.3.3 has been released, which includes fixes for https://github.com/pallets/click/issues/3084 and https://github.com/pallets/click/issues/3111 but the problem is still present with that version

**Comment by freakboy3742** [comment]
pallets/click#3403 tracks the MkDocs-specific manifestation of this issue.

**Comment by jaywhj** [comment]
> Please check it out! It's a complete drop-in replacement, you just `pip install properdocs` instead.
> 
> * https://github.com/ProperDocs/properdocs
> * https://github.com/ProperDocs/properdocs/discussions/33


MkDocs is no longer maintained or updated. Try **Properdocs** instead, it is a continuation of mkdocs 1.6.1 and fixes the series of bugs mentioned above.

Users who are still using mkdocs-material may also want to try [MaterialX](https://jaywhj.github.io/mkdocs-materialx/differences), the next-generation version of mkdocs-material. It is based on mkdocs-material 9.7 and has now been updated to version `10.1.x` .

**Comment by johnthagen** [comment]
This issue was fixed in Click 8.4.0

- https://github.com/pallets/click/issues/3403
- https://github.com/pallets/click/pull/3404
